### ISSUE TITLE
Autocomplete matplotlib crashes with py2 interpreter

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#11]
the python 2 interpreter in pythonista 3 crashes when autocompleting matplotlib commands from the editor.

```
#!python2
import matplotlib.pyplot as plt
```

Saving the file, reopening it, the. 
typing `plt.` on the next line causes a very long wait while matplot lib is i ported by jedi.  Finally, when jedi is done importing, pythonista crashes, Segmentation fault, the uncaughtexceptionhandler does not return anything.

**Comment by jsbain** [comment]
as an aside, there seems to be something sketchy with how jedi is working.  Calling jedi from the console on the same completion results in a completion, in about 8 seconds, vs 30+ from the editor

    jedi.Script('import matplotlib.pyplot as plt\nplt.').completions()

**Comment by omz** [comment]
I've tracked down the crashes, and they should be fixed in the next beta.

So far, I don't know why the built-in Jedi completion sometimes takes significantly longer than an equivalent script that uses the `jedi` module.

**Comment by rnhmjoj** [comment]
Has the fix been pushed? I'm still seeing this and it's really annoying.

**Comment by jsbain** [comment]
Seems to b fixed in recent appstore version
