### ISSUE TITLE
On 11” iPad Pro with physical keyboard input area is obscured while typing

### ISSUE THREAD

**Issue by steveko** [omz/Pythonista-Issues#575]
On the brand new 11” iPad Pro, when typing in the console area with the physical keyboard in landscape mode, the input area is obscured by the “special characters” palette.

**Comment by kkk669** [comment]
My 3rd generation 12.9” iPad Pro is the same.
![3d52dc2d-db4e-4244-b83e-98f610fb244b](https://user-images.githubusercontent.com/601636/48970773-b128e800-f053-11e8-9c04-c9aed096ae5a.jpeg)

**Comment by NetanelRabinowitz** [comment]
Is there any workaround to hide that extra keyboard line until it fixed?

**Comment by omz** [comment]
Yes, you can disable the "Shortcuts" option in the settings app (under General > Keyboard).

**Comment by NetanelRabinowitz** [comment]
Thanks!

**Comment by mikaeladlers** [comment]
Can not find the setting. I’m running 320000.
I have noted that others are running a newer version, it that is so why can I not download it from AppStore (I live in Sweden).

Thanks

**Comment by cclauss** [comment]
@mikaeladlers I think you need to be in the beta program to have this option.

**Comment by omz** [comment]
You don't have to be in the beta to have this option. Actually, you don't need this option in the beta because the bug this option supposed to work around should be fixed there.

**Comment by cclauss** [comment]
Tap on “Keyboard & Typing”

**Comment by omz** [comment]
No, the option is in the **Settings app**, not in Pythonista.

**Comment by omz** [comment]
If you’re interested in the beta, you can sign up here: https://testflight.apple.com/join/qDkBu2ur (the signup process is automatic, I don’t need your email address for this anymore).

**Comment by ooaklee** [comment]
Hey @omz, is there going to be any attempt to fix this bug? As I am still experiencing this issue when using my iPad Pro.

**Comment by jr-pe** [comment]
@ooaklee this bug is fixed in the v3.3 Beta
You can download the Beta using Testflight at the link @omz provided

**Comment by ooaklee** [comment]
Not sure how I missed that, thanks @jr-pe!

**Comment by Rfalvis** [comment]
Hello.  I have the brydge keyboard on my ipad 11 pro and this keyboard issue still going on.  I do not want to turn it off via ‘General > Keyboard’ setting as I need this feature enable in my ipad when accessing websites that require login information.  I tried signing up for the beta but it is no longer available.
Is there any future plans to fix this?  @omz

**Comment by johndrummond** [comment]
Same problem for me. How close is 3.3 to release?

**Comment by papermonkey** [comment]
Just discovered this as well as I just purchased an iPad Pro (2018) 12.9” and also purchased Pythonista. Is there any way to be included in the 3.3 Beta by chance? Or any updates to the new release? Since disabling Shortcuts is not preferable as it comes in handy for other applications.

**Comment by omz** [comment]
I'm finalizing the last couple of things and plan to submit to Apple this week.
